### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by WulffHunter** [ryvnf/tmacros#1]
Hey there, I'm really interested in using the vector.h macros! What kind of licensing will you allow? Or is this for your personal/private use?

**Comment by ryvnf** [comment]
Hello!

I am happy that someone is interested in using the code I and will not stop you from doing that.

I have now added a [license](http://unlicense.org/) which allows you to use the code with no restriction.

**Comment by WulffHunter** [comment]
Awesome! Thanks man! I look forward to being able to use vectors in my C game! Thanks for building and releasing this, it looks great and highly optimized.

**Comment by ryvnf** [comment]
Your welcome!
